services:
  elevators-system-backend:
    image: pploszczyca/elevators-system-backend
    ports: 
      - 9000:9000
  
  elevators-system-frontend:
    image: pploszczyca/elevators-system-frontend
    ports: 
      - 3000:3000
    environment:
      REACT_APP_PROXY_TARGET: http://elevators-system-backend:9000
