// export const HOST = "http://127.0.0.1:8080/"
export const ELEVATORS_PATH = "/elevators"
export const PICKUP_PATH = "/elevators/pickup"
export const UPDATE_PATH = "/elevators/update"
export const STEP_PATH = "/elevators/step"
